version: "3"
services: 
  db: 
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql 
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/docker_rails_test  # Railsアプリケーションのソースコードをマウント

volumes:
  mariadb-data:  # MariaDBのデータを保存するボリューム

