version: "3"
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    ports:
      - "8800:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      TZ: Asia/Tokyo
      JAVA_OPTS: -Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      user: "1000:1000"
volumes:
  jenkins-data: