version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
    volumes:
      - mariadb-data:/var/lib/mysql
  php:
    build:
        dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8880:80"
    volumes:
      - ./src:/var/www/html
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: testuser
      PMA_PASSWORD: testpass
    ports:
      - "4440:80"
    volumes:
      - phpmyadmin-data:/sessions
volumes:
  mariadb-data:
  phpmyadmin-data:



