version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kensyo

  locust:
    image: locustio/locust:latest
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    depends_on:
      - nginx
    command: -f /mnt/locust/locustfile.py --host http://nginx
    ports:
      - "8089:8089"
    networks:
      - kensyo

networks:
  kensyo: