global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_file:
- /etc/prometheus/alert.rules

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets:
      - prometheus: 9090

